# Site settings
title: "Home Page of Laksh Arora"
description: "Website of Laksh Arora including blogs , projects and resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_blog:                    "/blog"
resume_link:                    "arora_laksh_datascience_resume.pdf"    
resume_projects:                    "/projects"
resume_avatar:                  "true"
resume_name:                    "Laksh Arora"
resume_title:                   ""
resume_contact_email:           "laksharora28@gmail.com"
resume_header_contact_info: "B-129 Hari Nagar, New Delhi | +919871569215 | laksharora28@gmail.com"
resume_header_intro: "<p>Laksh Arora is Pythonista at heart and has interests in applications of Machine Learning and Computer Vision. Completed his BCA in Computer Science from IPU. Co-organiser of PyDataDelhi meetups. Previously also gave talk at PyDataDelhi community, CSI and other various small meetups. Also spoke at University level about latest work in Machine Learning and won multiple hackathons. Currently Associate Instructor at coding blocks where he is teaching Machine Learning and also collaborating with other enthusiasts over the globe doing independent projects. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"
got_skills_to_write_blog:       "no"
made_any_projects:              "no"
resume_pdf:                     "yes"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      true
# resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/techedlaksh"
  resume_twitter_url:           "http://twitter.com/techedlaksh"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/techedlaksh"
  resume_linkedin_url:          "https://www.linkedin.com/in/techedlaksh"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://laksharora.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

#Google Services
google_analytics: UA-51355623-2